version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    # command: python3 django-admin.py runserver 0.0.0.0:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      # - .:/code
      - ./app:/app
    ports:
      - "8001:8000"
    depends_on:
      - db


